import { AiFillStar } from "react-icons/ai";
const products = [
  {
    img: "https://obvi.com.ua/content/images/17/494x290l80mc0/originalnye-krossovki-nike-air-monarch-iv-415445-001-66901741288721.webp",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_SX535_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://cdn.etrias.nl/media/cache/product_thumb_md/1/7/17880111-waffle-one-black-white-light-menta-whitephpvpkmzm.jpg",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "120",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://img.eobuwie.cloud/eob_product_512w_512h(8/f/0/b/8f0becdc5e36e33eb473bef70f66ace8b44aeca5_0000300115930_01_ph.jpg,jpg)/buty-nike-air-zoom-pegasus-37-bq9646-011-off-noir-lt-blue-fury-0000300115930.jpg",
    title: "Nike Air Zoom Pegasus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(183 reviews)",
    prevPrice: "$140,00",
    newPrice: "120",
    company: "Nike",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://www.xylondon.com/cdn/shop/files/dsc_0641_2_1_aa90e021-1145-4621-ba73-ea7ed1c341bd.jpg?v=1704877759",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(197 reviews)",
    prevPrice: "$170,00",
    newPrice: "150",
    company: "Flats",
    color: "green",
    category: "vans",
  },
  {
    img: "https://deichmann.scene7.com/asset/deichmann/p_img_dm/1844680_P.jpg?defaultImage=default&wid=1000&hei=800",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(96 reviews)",
    prevPrice: "$160,00",
    newPrice: "140",
    company: "Vans",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/319H8IKzPKL._AC_SY300_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(96 reviews)",
    prevPrice: "$180,00",
    newPrice: "175",
    company: "Vans",
    color: "white",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_SY200_QL15_.jpg",
    title: "Puma Black-oce",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(96 reviews)",
    prevPrice: "$160,00",
    newPrice: "110",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
];

export default products;
